### ISSUE TITLE
TowerCompatExt can not work with tonic 0.8.4

### ISSUE THREAD

**Issue by youngsofun** [poem-web/poem#543]
## Expected Behavior

 examples/poem/tonic can build with latest tonic

## Actual Behavior

```
43  |     T: Codec,
    |        ^^^^^ required by this bound in `Grpc::<T>::unary`

error[E0277]: the trait bound `HelloReply: prost::message::Message` is not satisfied
   --> /Users/yangxiufeng/work/poem/examples/target/debug/build/example-tonic-b34d67536105198d/out/helloworld.rs:201:30
    |
201 | ...                   .apply_compression_config(
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `prost::message::Message` is not implemented for `HelloReply`
    |
    = help: the following other types implement trait `prost::message::Message`:
              ()
              Box<M>
              String
              Vec<u8>
              bool
              f32
              f64
              i32
            and 4 others
    = note: required for `ProstCodec<HelloReply, HelloRequest>` to implement `Codec`
note: required by a bound in `tonic::server::Grpc::<T>::apply_compression_config`
   --> /Users/yangxiufeng/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonic-0.8.3/src/server/grpc.rs:43:8
    |
43  |     T: Codec,
    |        ^^^^^ required by this bound in `Grpc::<T>::apply_compression_config`

error[E0277]: the trait bound `HelloRequest: prost::message::Message` is not satisfied
   --> /Users/yangxiufeng/work/poem/examples/target/debug/build/example-tonic-b34d67536105198d/out/helloworld.rs:201:30
    |
201 | ...                   .apply_compression_config(
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `prost::message::Message` is not implemented for `HelloRequest`
    |
    = help: the following other types implement trait `prost::message::Message`:
              ()
              Box<M>
              String
              Vec<u8>
              bool
              f32
              f64
              i32
            and 4 others
    = note: required for `ProstCodec<HelloReply, HelloRequest>` to implement `Codec`
note: required by a bound in `tonic::server::Grpc::<T>::apply_compression_config`
   --> /Users/yangxiufeng/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonic-0.8.3/src/server/grpc.rs:43:8
    |
43  |     T: Codec,
    |        ^^^^^ required by this bound in `Grpc::<T>::apply_compression_config`

error[E0277]: the trait bound `HelloReply: prost::message::Message` is not satisfied
   --> /Users/yangxiufeng/work/poem/examples/target/debug/build/example-tonic-b34d67536105198d/out/helloworld.rs:200:65
    |
200 |                         let mut grpc = tonic::server::Grpc::new(codec)
    |                                        ------------------------ ^^^^^ the trait `prost::message::Message` is not implemented for `HelloReply`
    |                                        |
    |                                        required by a bound introduced by this call
    |
    = help: the following other types implement trait `prost::message::Message`:
              ()
              Box<M>
              String
              Vec<u8>
              bool
              f32
              f64
              i32
            and 4 others
    = note: required for `ProstCodec<HelloReply, HelloRequest>` to implement `Codec`
note: required by a bound in `tonic::server::Grpc::<T>::new`
   --> /Users/yangxiufeng/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonic-0.8.3/src/server/grpc.rs:43:8
    |
43  |     T: Codec,
    |        ^^^^^ required by this bound in `Grpc::<T>::new`

error[E0277]: the trait bound `HelloRequest: prost::message::Message` is not satisfied
   --> /Users/yangxiufeng/work/poem/examples/target/debug/build/example-tonic-b34d67536105198d/out/helloworld.rs:200:65
    |
200 |                         let mut grpc = tonic::server::Grpc::new(codec)
    |                                        ------------------------ ^^^^^ the trait `prost::message::Message` is not implemented for `HelloRequest`
    |                                        |
    |                                        required by a bound introduced by this call
    |
    = help: the following other types implement trait `prost::message::Message`:
              ()
              Box<M>
              String
              Vec<u8>
              bool
              f32
              f64
              i32
            and 4 others
    = note: required for `ProstCodec<HelloReply, HelloRequest>` to implement `Codec`
note: required by a bound in `tonic::server::Grpc::<T>::new`
   --> /Users/yangxiufeng/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonic-0.8.3/src/server/grpc.rs:43:8
    |
43  |     T: Codec,
    |        ^^^^^ required by this bound in `Grpc::<T>::new`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `example-tonic` (bin "example-tonic-client") due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
error[E0277]: `(dyn axum::boxed::ErasedIntoRoute<(), tonic::transport::Body, Infallible> + 'static)` cannot be shared between threads safely
  --> poem/tonic/src/main.rs:39:14
   |
39 |             .compat(),
   |              ^^^^^^ `(dyn axum::boxed::ErasedIntoRoute<(), tonic::transport::Body, Infallible> + 'static)` cannot be shared between threads safely
   |
   = help: the trait `Sync` is not implemented for `(dyn axum::boxed::ErasedIntoRoute<(), tonic::transport::Body, Infallible> + 'static)`
   = note: required for `Unique<(dyn axum::boxed::ErasedIntoRoute<(), tonic::transport::Body, Infallible> + 'static)>` to implement `Sync`
   = note: required because it appears within the type `Box<dyn ErasedIntoRoute<(), Body, Infallible>>`
   = note: required because it appears within the type `BoxedIntoRoute<(), Body, Infallible>`
   = note: required because it appears within the type `Fallback<(), Body>`
   = note: required because it appears within the type `Router`
   = note: required because it appears within the type `Routes`
note: required by a bound in `poem::endpoint::TowerCompatExt::compat`
  --> /Users/yangxiufeng/work/poem/poem/src/endpoint/tower_compat.rs:26:15
   |
26 |             + Sync
   |               ^^^^ required by this bound in `TowerCompatExt::compat`

error[E0277]: `(dyn tower::util::boxed_clone::CloneService<poem::http::Request<tonic::transport::Body>, Future = Pin<Box<(dyn Future<Output = Result<poem::http::Response<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, axum_core::error::Error>>, Infallible>> + Send + 'static)>>, Response = poem::http::Response<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, axum_core::error::Error>>, Error = Infallible> + Send + 'static)` cannot be shared between threads safely
  --> poem/tonic/src/main.rs:39:14
   |
39 |             .compat(),
   |              ^^^^^^ `(dyn tower::util::boxed_clone::CloneService<poem::http::Request<tonic::transport::Body>, Future = Pin<Box<(dyn Future<Output = Result<poem::http::Response<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, axum_core::error::Error>>, Infallible>> + Send + 'static)>>, Response = poem::http::Response<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, axum_core::error::Error>>, Error = Infallible> + Send + 'static)` cannot be shared between threads safely
   |
   = help: the trait `Sync` is not implemented for `(dyn tower::util::boxed_clone::CloneService<poem::http::Request<tonic::transport::Body>, Future = Pin<Box<(dyn Future<Output = Result<poem::http::Response<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, axum_core::error::Error>>, Infallible>> + Send + 'static)>>, Response = poem::http::Response<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, axum_core::error::Error>>, Error = Infallible> + Send + 'static)`
   = note: required for `Unique<dyn CloneService<Request<Body>, Future = Pin<Box<dyn Future<Output = Result<Response<UnsyncBoxBody<Bytes, Error>>, Infallible>> + Send>>, Response = ..., Error = ...> + Send>` to implement `Sync`
   = note: the full type name has been written to '/Users/yangxiufeng/work/poem/examples/target/debug/deps/example_tonic-9fb8ae317674c066.long-type-2187458231224480910.txt'
   = note: required because it appears within the type `Box<dyn CloneService<Request<Body>, Future = Pin<Box<dyn Future<Output = Result<Response<UnsyncBoxBody<Bytes, Error>>, Infallible>> + Send>>, Response = Response<UnsyncBoxBody<Bytes, Error>>, Error = Infallible> + Send>`
   = note: required because it appears within the type `BoxCloneService<Request<Body>, Response<UnsyncBoxBody<Bytes, Error>>, Infallible>`
   = note: required because it appears within the type `Route`
   = note: required because it appears within the type `Fallback<(), Body>`
   = note: required because it appears within the type `Router`
   = note: required because it appears within the type `Routes`
note: required by a bound in `poem::endpoint::TowerCompatExt::compat`
  --> /Users/yangxiufeng/work/poem/poem/src/endpoint/tower_compat.rs:26:15
   |
26 |             + Sync
   |               ^^^^ required by this bound in `TowerCompatExt::compat`

error[E0277]: `(dyn axum::boxed::ErasedIntoRoute<(), tonic::transport::Body, Infallible> + 'static)` cannot be shared between threads safely
  --> poem/tonic/src/main.rs:34:28
   |
34 |     let app = Route::new().nest_no_strip(
   |                            ^^^^^^^^^^^^^ `(dyn axum::boxed::ErasedIntoRoute<(), tonic::transport::Body, Infallible> + 'static)` cannot be shared between threads safely
   |
   = help: the trait `Sync` is not implemented for `(dyn axum::boxed::ErasedIntoRoute<(), tonic::transport::Body, Infallible> + 'static)`
   = note: required for `Unique<(dyn axum::boxed::ErasedIntoRoute<(), tonic::transport::Body, Infallible> + 'static)>` to implement `Sync`
   = note: required because it appears within the type `Box<dyn ErasedIntoRoute<(), Body, Infallible>>`
   = note: required because it appears within the type `BoxedIntoRoute<(), Body, Infallible>`
   = note: required because it appears within the type `Fallback<(), Body>`
   = note: required because it appears within the type `Router`
   = note: required because it appears within the type `Routes`
   = note: required for `endpoint::tower_compat::TowerCompatEndpoint<Routes>` to implement `poem::Endpoint`
   = note: required for `endpoint::tower_compat::TowerCompatEndpoint<Routes>` to implement `IntoEndpoint`

error[E0277]: `(dyn tower::util::boxed_clone::CloneService<poem::http::Request<tonic::transport::Body>, Future = Pin<Box<(dyn Future<Output = Result<poem::http::Response<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, axum_core::error::Error>>, Infallible>> + Send + 'static)>>, Response = poem::http::Response<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, axum_core::error::Error>>, Error = Infallible> + Send + 'static)` cannot be shared between threads safely
  --> poem/tonic/src/main.rs:34:28
   |
34 |     let app = Route::new().nest_no_strip(
   |                            ^^^^^^^^^^^^^ `(dyn tower::util::boxed_clone::CloneService<poem::http::Request<tonic::transport::Body>, Future = Pin<Box<(dyn Future<Output = Result<poem::http::Response<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, axum_core::error::Error>>, Infallible>> + Send + 'static)>>, Response = poem::http::Response<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, axum_core::error::Error>>, Error = Infallible> + Send + 'static)` cannot be shared between threads safely
   |
   = help: the trait `Sync` is not implemented for `(dyn tower::util::boxed_clone::CloneService<poem::http::Request<tonic::transport::Body>, Future = Pin<Box<(dyn Future<Output = Result<poem::http::Response<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, axum_core::error::Error>>, Infallible>> + Send + 'static)>>, Response = poem::http::Response<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, axum_core::error::Error>>, Error = Infallible> + Send + 'static)`
   = note: required for `Unique<dyn CloneService<Request<Body>, Future = Pin<Box<dyn Future<Output = Result<Response<UnsyncBoxBody<Bytes, Error>>, Infallible>> + Send>>, Response = ..., Error = ...> + Send>` to implement `Sync`
   = note: the full type name has been written to '/Users/yangxiufeng/work/poem/examples/target/debug/deps/example_tonic-9fb8ae317674c066.long-type-2187458231224480910.txt'
   = note: required because it appears within the type `Box<dyn CloneService<Request<Body>, Future = Pin<Box<dyn Future<Output = Result<Response<UnsyncBoxBody<Bytes, Error>>, Infallible>> + Send>>, Response = Response<UnsyncBoxBody<Bytes, Error>>, Error = Infallible> + Send>`
   = note: required because it appears within the type `BoxCloneService<Request<Body>, Response<UnsyncBoxBody<Bytes, Error>>, Infallible>`
   = note: required because it appears within the type `Route`
   = note: required because it appears within the type `Fallback<(), Body>`
   = note: required because it appears within the type `Router`
   = note: required because it appears within the type `Routes`
   = note: required for `endpoint::tower_compat::TowerCompatEndpoint<Routes>` to implement `poem::Endpoint`
   = note: required for `endpoint::tower_compat::TowerCompatEndpoint<Routes>` to implement `IntoEndpoint`

error: could not compile `example-tonic` (bin "example-tonic") due to 12 previous errors
```

## Steps to Reproduce the Problem

1.   cd `cargo build` in /examples/poem/tonic
2.  edit [Cargo.toml](https://github.com/poem-web/poem/blob/master/examples/poem/tonic/Cargo.toml#L11) change version of tonic and tonic-build to 0.8.4
3.  `cargo build`

```


## Specifications

- Version:
- Platform:
- Subsystem:

**Comment by youngsofun** [comment]
seems related to https://github.com/poem-web/poem/issues/542
