### ISSUE TITLE
poem-openapi: `operation_id` doesn't work with `transform`

### ISSUE THREAD

**Issue by DDtKey** [poem-web/poem#405]
## Expected Behavior
I want to specify `operation_id`& add `transform` to my endpoint.
The code below should work fine:
```rust
struct Api;

#[OpenApi]
impl Api {
    #[oai(path = "/hello", method = "get", operation_id = "hello", transform = "my_transformer")]
    async fn index(&self) -> PlainText<String> {
        PlainText(format!("hello, world!"))
    }
}

fn my_transformer(ep: impl Endpoint) -> impl Endpoint {
    ep.with(MyMiddleware::new())
}
```

## Actual Behavior

It returns error:
```
error[E0599]: no method named `set_data` found for mutable reference `&mut <impl poem::Endpoint as poem::Endpoint>::Output` in the current scope

| #[OpenApi]
| ^^^^^^^^^ method not found in `&mut <impl poem::Endpoint as poem::Endpoint>::Output`

```

Looks like it was broken after #351 
It perfectly works on `poem-openapi 2.0.7`

## Specifications

- Version: `poem: 1.3.45` + `poem-openapi: 2.0.15`

**Comment by sunli829** [comment]
Fixed in `v2.0.16` 🙂

**Comment by DDtKey** [comment]
Thank you for such quick-fix!
